CREATE TABLE cat_estados(id_estado VARCHAR(10),estado VARCHAR(10));
INSERT INTO cat_estados (id_estado,estado) VALUES ('001','AGUASCALIENTES');
INSERT INTO cat_estados (id_estado,estado) VALUES ('002','BAJA CALIFORNIA');
INSERT INTO cat_estados (id_estado,estado) VALUES ('003','BAJA CALIFORNIA SUR');
INSERT INTO cat_estados (id_estado,estado) VALUES ('004','CAMPECHE');
INSERT INTO cat_estados (id_estado,estado) VALUES ('005','COAHUILA DE ZARAGOZA');
INSERT INTO cat_estados (id_estado,estado) VALUES ('006','COLIMA');
INSERT INTO cat_estados (id_estado,estado) VALUES ('007','CHIAPAS');
INSERT INTO cat_estados (id_estado,estado) VALUES ('008','CHIHUAHUA');
INSERT INTO cat_estados (id_estado,estado) VALUES ('009','DISTRITO FEDERAL');
INSERT INTO cat_estados (id_estado,estado) VALUES ('010','DURANGO');
INSERT INTO cat_estados (id_estado,estado) VALUES ('011','GUANAJUATO');
INSERT INTO cat_estados (id_estado,estado) VALUES ('012','GUERRERO');
INSERT INTO cat_estados (id_estado,estado) VALUES ('013','HIDALGO');
INSERT INTO cat_estados (id_estado,estado) VALUES ('014','JALISCO');
INSERT INTO cat_estados (id_estado,estado) VALUES ('015','MEXICO');
INSERT INTO cat_estados (id_estado,estado) VALUES ('016','MICHOACAN DE OCAMPO');
INSERT INTO cat_estados (id_estado,estado) VALUES ('017','MORELOS');
INSERT INTO cat_estados (id_estado,estado) VALUES ('018','NAYARIT');
INSERT INTO cat_estados (id_estado,estado) VALUES ('019','NUEVO LEON');
INSERT INTO cat_estados (id_estado,estado) VALUES ('020','OAXACA');
INSERT INTO cat_estados (id_estado,estado) VALUES ('021','PUEBLA');
INSERT INTO cat_estados (id_estado,estado) VALUES ('022','QUERETARO DE ARTEAGA');
INSERT INTO cat_estados (id_estado,estado) VALUES ('023','QUINTANA ROO');
INSERT INTO cat_estados (id_estado,estado) VALUES ('024','SAN LUIS POTOSI');
INSERT INTO cat_estados (id_estado,estado) VALUES ('025','SINALOA');
INSERT INTO cat_estados (id_estado,estado) VALUES ('026','SONORA');
INSERT INTO cat_estados (id_estado,estado) VALUES ('027','TABASCO');
INSERT INTO cat_estados (id_estado,estado) VALUES ('028','TAMAULIPAS');
INSERT INTO cat_estados (id_estado,estado) VALUES ('029','TLAXCALA');
INSERT INTO cat_estados (id_estado,estado) VALUES ('030','VERACRUZ DE IGNACIO DE LA LLAVE');
INSERT INTO cat_estados (id_estado,estado) VALUES ('031','YUCATAN');
INSERT INTO cat_estados (id_estado,estado) VALUES ('032','ZACATECAS');
INSERT INTO cat_estados (id_estado,estado) VALUES ('033','ENTIDAD FEDERATIVA NO ESPECIFICADA');
