CREATE TABLE cat_municipios(id_municipio INT,municipio VARCHAR(50));
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (1,'Acajete');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (2,'Acatlán');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (3,' Acayucan');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (4,'Actopan');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (5,' Acula');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (6,'Acultzingo');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (7,'Camarón de Tejeda');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (8,'Alpatláhuac');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (9,'Alto Lucero de Gutiérrez Barrios');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (10,' Altotonga');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (11,' Alvarado');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (12,' Amatitlán');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (13,'Naranjos Amatlán');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (14,'Amatlán de los Reyes');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (15,'Angel R. Cabada');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (16,'La Antigua');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (17,'Apazapan');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (18,'Aquila');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (19,'Astacinga');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (20,'Atlahuilco');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (21,'Atoyac');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (22,'Atzacan');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (23,'Atzalan');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (24,'Tlaltetela');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (25,'Ayahualulco');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (26,'Banderilla');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (27,'Benito Juárez');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (28,'Boca del Río');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (29,'Calcahualco');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (30,'Camerino Z. Mendoza');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (31,'Carrillo Puerto');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (32,'Catemaco');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (33,'Cazones');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (34,'Cerro Azul');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (35,'Citlaltépetl');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (36,'Coacoatzintla');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (37,'Coahuitlán');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (38,'Coatepec');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (39,'Coatzacoalcos');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (40,'Coatzintla');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (41,'Coetzala');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (42,'Colipa');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (43,'Comapa');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (44,'Córdoba');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (45,'Cosamaloapan de Carpio');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (46,'Cosautlán de Carvajal');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (47,'Coscomatepec');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (48,'Cosoleacaque');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (49,'Cotaxtla');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (50,'Coxquihui');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (51,'Mariano Escobedo');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (52,'Martínez de la Torre');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (53,'Mecatlán');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (54,'Mecayapan');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (55,'Medellín');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (56,'Miahuatlán');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (57,'Las Minas');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (58,'Minatitlán');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (59,'Misantla');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (60,'Mixtla de Altamirano');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (61,'Chacaltianguis');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (62,'Chalma');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (63,'Chiconamel');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (64,'Chiconquiaco');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (65,'Chicontepec');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (66,'Chinameca');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (67,'Chinampa de Gorostiza');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (68,'Las Choapas');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (69,'Chocamán');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (70,'Chontla');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (71,'Chumatlán');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (72,'Emiliano Zapata');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (73,'Espinal');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (74,'Filomeno Mata');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (75,'Fortín');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (76,'Gutiérrez Zamora');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (77,'Hidalgotitlán');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (78,'Huatusco');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (79,'Huayacocotla');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (80,'Hueyapan de Ocampo');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (81,'Huiloapan');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (82,'Ignacio de la Llave');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (83,'Ilamatlán');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (84,'Isla');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (85,'Ixcatepec');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (86,'Ixhuacán de los Reyes');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (87,'Ixhuatlán del Café');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (88,'Ixhuatlancillo');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (89,'Ixhuatlán del Sureste');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (90,'Ixhuatlán de Madero');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (91,'Ixmatlahuacan');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (92,'Ixtaczoquitlán');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (93,'Jalacingo');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (94,'Xalapa');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (95,'Jalcomulco');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (96,'Jáltipan');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (97,'Jamapa');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (98,'Jesús Carranza');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (99,'Xico');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (100,'Jilotepec');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (101,'Juan Rodríguez Clara');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (102,'Juchique de Ferrer');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (103,'Landero y Coss');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (104,'Lerdo de Tejada');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (105,'Magdalena');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (106,'Maltrata');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (107,'Manlio Fabio Altamirano');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (108,'Coyutla');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (109,'Cuichapa');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (110,'Cuitláhuac');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (111,'Moloacán');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (112,'Naolinco');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (113,'Naranjal');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (114,'Nautla');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (115,' Nogales');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (116,'Oluta');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (117,'Omealca');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (118,'Orizaba');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (119,'Otatitlán');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (120,'Oteapan');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (121,'Ozuluama de Mascare±as');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (122,'Pajapan');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (123,'Pánuco');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (124,'Papantla');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (125,'Paso del Macho');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (126,'Paso de Ovejas');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (127,'La Perla');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (128,'Perote');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (129,'Platón Sánchez');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (130,'Playa Vicente');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (131,'Poza Rica de Hidalgo');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (132,'Las Vigas de Ramírez');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (133,'Pueblo Viejo');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (134,'Puente Nacional');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (135,'Rafael Delgado');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (136,'Rafael Lucio');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (137,'Los Reyes');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (138,'Río Blanco');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (139,'Saltabarranca');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (140,' San Andrés Tenejapan');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (141,'San Andrés Tuxtla');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (142,'San Juan Evangelista');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (143,'Santiago Tuxtla');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (144,'Sayula de Alemán');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (145,'Soconusco');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (146,'Sochiapa');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (147,'Soledad Atzompa');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (148,'Soledad de Doblado');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (149,'Soteapan');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (150,'Tamalín');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (151,' Tamiahua');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (152,'Tampico Alto');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (153,' Tancoco');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (154,'Tantima');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (155,'Tantoyuca');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (156,'Tatatila');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (157,'Castillo de Teayo');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (158,'Tecolutla');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (159,'Tehuipango');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (160,'Temapache');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (161,'Tempoal');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (162,'Tenampa');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (163,'Tenochtitlán');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (164,'Teocelo');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (165,'Tepatlaxco');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (166,'Tepetlán');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (167,'Tepetzintla');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (168,'Tequila');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (169,' José Azueta');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (170,' Texcatepec');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (171,'Texhuacán');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (172,' Texistepec');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (173,'Tezonapa');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (174,'Tierra Blanca');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (175,'Tihuatlán');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (176,'Tlacojalpan');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (177,' Tlacolulan');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (178,'Tlacotalpan');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (179,' Tlacotepec de Mejía');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (180,'Tlachichilco');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (181,'Tlalixcoyan');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (182,'Tlalnelhuayocan');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (183,'Tlapacoyan');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (184,' Tlaquilpa');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (185,'Tlilapan');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (186,'Tomatlán');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (187,'Tonayán');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (188,'Totutla');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (189,'Túxpam');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (190,'Tuxtilla');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (191,'Ursulo Galván');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (192,' Vega de Alatorre');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (193,'Veracruz');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (194,'Villa Aldama');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (195,'Xoxocotla');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (196,'Yanga');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (197,' Yecuatla');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (198,'Zacualpan');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (199,'Zaragoza');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (200,'Zentla');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (201,'Zongolica');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (202,'Zontecomatlán de López y Fuentes');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (203,'Zozocolco de Hidalgo');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (204,'Agua Dulce');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (205,'El Higo');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (206,'Nanchital de Lázaro Cárdenas del Río');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (207,'Tres Valles');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (208,'Carlos A. Carrillo');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (209,'Tatahuicapan de Juárez');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (210,'Uxpanapa');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (211,' San Rafael');
INSERT INTO cat_municipios (id_municipio,municipio) VALUES (212,'Santiago Sochiapan');
