INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (1,'esposa');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (2,'esposo');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (3,'hija');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (4,'hijo');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (5,'hija');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (6,'hijo');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (7,'madre');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (8,'padre');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (9,'hermana');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (10,'hermano');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (11,'sobrina');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (12,'sobrino');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (13,'abuela');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (14,'abuelo');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (15,'tía');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (16,'tío');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (17,'prima');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (18,'primo');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (19,'sobrina segunda');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (20,'sobrino segundo');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (21,'bisabuela');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (22,'bisabuelo');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (23,'tía-abuela');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (24,'tío-abuelo');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (25,'tía segunda');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (26,'tío segundo');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (27,'prima segunda');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (28,'primo segundo');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (29,'sobrina tercera');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (30,'sobrino tercero');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (31,'tatarabuela');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (32,'tatarabuelo');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (33,'tía-bisabuela');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (34,'tío-bisabuelo');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (35,'tía-abuela segunda');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (36,'tío-abuelo segundo');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (37,'tía tercera');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (38,'tío tercero');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (39,'prima tercera');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (40,'primo tercero');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (41,'sobrina cuarta');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (42,'sobrino cuarto');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (43,'cuñada');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (44,'cuñado');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (45,'hija');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (46,'hijo');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (47,'hijastra');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (48,'hijastro');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (49,'suegra');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (50,'suegro');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (51,'cuñada');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (52,'cuñado');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (53,'sobrina política');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (54,'sobrino político');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (55,'abuela política (prosuegra)');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (56,'abuelo político (prosuegro)');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (57,'tía política');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (58,'tío político');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (59,'prima política');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (60,'primo político');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (61,'sobrina segunda política');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (62,'sobrino segundo político');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (63,'bisabuela política (absuegra)');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (64,'bisabuelo político (absuegro)');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (65,'tía-abuela política');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (66,'tío-abuelo político');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (67,'tía segunda política');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (68,'tío segundo político');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (69,'prima segunda política');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (70,'primo segundo político');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (71,'sobrina tercera política');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (72,'sobrino tercero político');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (73,'tatarabuela política');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (74,'tatarabuelo político');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (75,'tía-bisabuela política');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (76,'tío-bisabuelo político');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (77,'tía-abuela segunda política');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (78,'tío-abuelo segundo político');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (79,'tía tercera política');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (80,'tío tercero político');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (81,'tía tercera política');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (82,'primo tercero político');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (83,'sobrina cuarta política');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (84,'sobrino cuarto político');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (85,'prima política');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (86,'primo político');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (87,'sobrina');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (88,'sobrino');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (89,'sobrinastra');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (90,'sobrinastro');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (91,'sobrina segunda');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (92,'sobrino segundo');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (93,'sobrinastra segunda');
INSERT INTO cat_parentescos (id_parentesco,parentesco) VALUES (94,'sobrinastro segundo');
